websocket-dashboard:
  restart: always
  build: ./cmd
  env_file:
    - ./websocket-dashboard.env
  ports:
    - "8080:8080"
  links:
    - postgres:postgres
  # command: websocket-dashboard-linux

postgres:
  restart: always
  build: ./postgres
  env_file:
    - ./postgres.env
  ports:
    - "32770:5432"
