websocket-dashboard:
  # restart: always
  build: ./cmd
  env_file:
    - ./websocket-dashboard.env
  ports:
    - "8080:8080"
  links:
    - postgres:postgres
    - redis:redis
  # command: "/usr/bin/tail -f /dev/null"

postgres:
  restart: always
  build: ./postgres
  env_file:
    - ./postgres.env
  ports:
    - "32770:5432"

redis:
  restart: always
  build: ./redis
  ports:
    - "32772:6379"
